version: "3.7"

services:
  db:
    container_name: db
    env_file:
      - .env
    restart: always
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    container_name: loanmax
    env_file:
      - .env
    restart: always
    build:
      context: .
      dockerfile: project/docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  mysql-data:
  flask-app-db:
    name: flask-app-db

